### ISSUE TITLE
Pop!_OS 24.04 ISO tracking issue (amd64)

### ISSUE THREAD

**Issue by XV-02** [pop-os/iso#326]
This Issue is for tracking issues with the initial release ISOs for the 24.04 derived release of Pop!_OS.

Edit this checklist as bugs are found and resolved. Create individual posts in this issue for each bug as it occurs. (Checkmarks are no longer problems)

### Outstanding Issues:
- [ ] [ISO does not reliably drop the user into the live-session](https://github.com/pop-os/iso/issues/326#issuecomment-2096989443)/gets stuck at cosmic-greeter
- [ ] [Nvidia Debug ISO issues](https://github.com/pop-os/iso/issues/333)
- [ ] [No initial setup](https://github.com/pop-os/iso/issues/326#issuecomment-2189810643)
- [ ] [Does not have tooling for GUI .deb installation](https://github.com/pop-os/iso/issues/326#issuecomment-2239434729)

### Resolved
- [x] [ISO requires network connection](https://github.com/pop-os/iso/issues/326#issuecomment-2096977750) to complete installation on real hardware
- [x] [Installer doesn't auto-launch](https://github.com/pop-os/iso/issues/326#issuecomment-2097002586)
- [x] [Cannot boot encrypted install](https://github.com/pop-os/iso/issues/326#issuecomment-2097006125)
- [x] [Flathub remotes not installed](https://github.com/pop-os/iso/issues/326#issuecomment-2101498015)
- [x] [ISO fails to reach GUI session on Nvidia desktops](https://github.com/pop-os/iso/issues/326#issuecomment-2176684066)

**Comment by XV-02** [comment]
###  ISO requires network:

While attempting to do an install on actual hardware without a network connection, the install errors out and fails. 

I've attached a copy of the install logs:

 The first [installer.log](https://github.com/pop-os/iso/files/15226873/installer.log) looks truncated by the installer dying during the install attempt.

The second [Install_attempt_02.log](https://github.com/pop-os/iso/files/15226854/Install_attempt_02.log) was pulled directly from the terminal output while running `sudo -E io.elementary.installer`

When I connect to wi-fi (which I have to do via cli, as the wi-fi applet doesn't seem to work as I would expect in the live session) the install progressed smoothly, however. 

Additionally, network connection of not, the install progresses smoothly on a virtual machine.

**Comment by XV-02** [comment]
### ISO doesn't land in live-user session reliably

When launching the live session, I have only seen the live disk drop into the live-user session once. 

In general, the process gets caught up on the login screen for cosmic-greeter. There is no obvious way to launch a session from the login screen. 

I'm not sure if that is due to the `pop-os` user not having a password, or if it is similar to an on-going issue where cosmic-greeter will hang after entering the user password and trying to launch a session. diagnostically, it looks the same at first blush.

My current workaround is to open a separate TTY (usually tty4 via `ctrl + alt + F4` ), login using the `pop-os` user, and launch `cosmic-session` directly before proceeding. 

This needs further investigation.

**Comment by XV-02** [comment]
### Installer doesn't auto-launch

This issue was highlighted by @jackpot51 

Currently, the workaround is to launch the installer from the terminal using `sudo -E io.elementary.installer`

**Comment by XV-02** [comment]
### Cannot boot encrypted install

While the encrypted install itself seems slightly unstable, when successfully completed, the system does not boot to a decrypt prompt of any kind afterwards. 

This requires additional investigation.

**Comment by WatchMkr** [comment]
The install does not boot on the oryp11 (hybrid nvidia). Boot stops at the Pop logo. The same result occurs for encrypted and unencrypted installs.
![oryp11-2404-boot](https://github.com/pop-os/iso/assets/3430283/c7bd91af-1c42-494f-ba47-c6b4505ba90d)

**Comment by WatchMkr** [comment]
The install does not boot on the oryp11 (hybrid nvidia). Boot stops at the Pop logo. The same result occurs for encrypted and unencrypted installs.
![oryp11-2404-boot](https://github.com/pop-os/iso/assets/3430283/339b7b20-c658-4c12-8269-a5a89473d7c7)

**Comment by WatchMkr** [comment]
Flathub remotes aren't installed

**Comment by jackpot51** [comment]
> Flathub remotes aren't installed

This would require running xdg autostarts.

**Comment by XV-02** [comment]
Testing debug 137 on a Thelio Major R4 with a 3060ti, I am seeing different behaviour. 

For the Nvidia ISO, cosmic-greeter does not start.
[Output for `systemctl status cosmic-greeter.service`](https://github.com/user-attachments/files/15890500/ISO137N_cosmicgreeterservice.log) (log file)
[Output from `sudo dmesg`](https://github.com/user-attachments/files/15890506/ISO137N_dmesg.log) (log file)
[Output from `journalctl -b 0`](https://github.com/user-attachments/files/15890515/ISO137N_journal.log) (log file)

For the Intel ISO, cosmic-greeter starts, but the system is completely unresponsive.

**Comment by XV-02** [comment]
Testing debug 145, the [desktop issues persist](https://github.com/pop-os/iso/issues/326#issuecomment-2176684066), but appear to be Nvidia specific. The behaviour is unchanged.

On a Mira B4 with an RX 6600 XT, the ISO successfully reaches a GUI session, auto-launches the installer, and installs.

**Comment by XV-02** [comment]
### No initial setup equivalent

From a feature-parity perspective, we don't have anything like `gnome-initial-setup` right now. 

Some configuration with GIS might not be needed right now: dock preferences, workspace/app-library buttons, clock position, dark/light mode, location services, online accounts.

But, two configurations jump out right away as missing: time-zone selection, and wi-fi setup. 

This is a UX question ultimately, and should probably have an application design drafted.

**Comment by XV-02** [comment]
The previously observed [issues for Nvidia ISO](https://github.com/pop-os/iso/issues/326#issuecomment-2176684066) are still present in debug ISO 167.

**Comment by thomas-zimmerman** [comment]
Eddy is not installed to handle 'deb' file installs. Currently "file roller" tries to open them.

**Comment by sund3RRR** [comment]
# Segfault when trying to select disk for installation
Intel/amd image.
Tech specs:
CPU: AMD Ryzen 7 5700x
GPU: AMD Radeon RX 6700XT
```
Sep 26 18:23:15 pop-os sudo[14587]: pam_unix(sudo:session): session closed for user root
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] Unaligned partial completion (resid=4060, sector_sz=512)
Sep 26 18:23:15 pop-os kernel: sd 7:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Sep 26 18:23:15 pop-os kernel: io.elementary.i[14528]: segfault at 10 ip 0000725936606178 sp 00007ffd10b9b460 error 4 in libdistinst.so[7259365e7000+29b000] likely on CPU 14 (core 6, socket 0)
Sep 26 18:23:15 pop-os kernel: Code: 48 bf 02 00 00 00 05 00 00 00 e8 33 cd ff ff 48 c7 44 24 08 00 00 00 00 48 c7 44 24 10 08 00 00 00 48 c7 44 24 18 00 00 00 00 <49> 8b 46 10 48 85 c0 0f 84 96 00 00 00 4d 8b 66 08 4c 69 e8s 88 02
Sep 26 18:23:15 pop-os systemd[2895]: app-cosmic-io.elementary.installer-14506.scope: Consumed 3.183s CPU time.
Sep 26 18:23:16 pop-os sudo[14601]:   pop-os : TTY=pts/1 ; PWD=/home/pop-os ; USER=root ; COMMAND=/usr/bin/journalctl -e
Sep 26 18:23:16 pop-os sudo[14601]: pam_unix(sudo:session): session opened for user root(uid=0) by pop-os(uid=1000)
```
